### ISSUE TITLE
Add dispatcher execution script on model of `crmp_download`

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/crmprtd#129]
Using a network argument, script `crmp_download` dispatches to the various per-network download scripts. We should do the same with the execution scripts. This will make `setup.py` fully static, setting us up for an easy transition to `pyproject.toml`.

**Comment by rod-glover** [comment]
I think I like that idea, especially as it seems to make the whole set of operations more testable. Investigating ...

**Comment by rod-glover** [comment]
I'm looking carefully at what `infill_all` (trivial) and `infill` (not so much) do. A few questions so far:

1. The network arg "ec_swob" is defined as partners ("bc_env_snow", "bc_tran", "bc_forestry"). Is that still right? Are there not more partners now?
2. The only networks handled are crd, ec, moti, wamr, wmb, ec_swob (see above). I believe this should be expanded, yes? 
3. And maybe that's what you meant (at least in part) by your alternative suggestion above to expand `infill` to do all the work of the shell scripts?

**Comment by jameshiebert** [comment]
> The network arg "ec_swob" is defined as partners ("bc_env_snow", "bc_tran", "bc_forestry"). Is that still right?

One could probably use `crmprtd.SWOB_PARTNERS` defined in the package-level `__init__.py`. Though one would probably want to break that up into provincial-level sets, since different networks typically go to different databases.

**Comment by rod-glover** [comment]
> One could probably use `crmprtd.SWOB_PARTNERS` defined in the package-level `__init__.py`. Though one would probably want to break that up into provincial-level sets, since different networks typically go to different databases.

Almost certainly; different database targets, and with that, different logging options.

I have enough now to start a branch/PR on this.
