### ISSUE TITLE
Problems in actual use

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/crmprtd#141]
- Default cache and log file names contain "~", which is not resolved (i.e., just treated as a non-special filepath character) when opening a file from Python. It's Linux that resolves it when using it on the command line, which is not happening here.
- Env vars (e.g., PATH) are not passed through to subprocesses, either in Python or in Linux. 
  - E.g., in Linux, in `XXX=xxx foo.sh | bar.sh` only `foo.sh` has `XXX` defined. A similar thing is true for Python suprocesses.run. For the latter, there is a simple way of forwarding the env vars, but it has to be explicitly done, and isn't (yet).
  - `cron`, however, seems to behave differently. I can demonstrate (on my Ubuntu 20.04 instance) that all subprocesses spawned by any script it invokes get all the env variables defined in the `crontab`. 
  - Further testing will show whether this is true of variables defined on individual cron job lines (e.g., `* * * * * XXX=xxx foo.sh`). But if this holds up it (a) is very convenient and (b) seems risky/fragile. It may be a bad idea to rely on it, unless it is a specified feature.
- It would help to have a do-nothing standard "test" network so we can invoke it without, uh, doing anything.
- The remaining scripts in `crmprtd/execution/` are not included in `pyproject.toml`

**Comment by jameshiebert** [comment]
>  It's Linux that resolves it 

Technically it's the *bash shell* that resolves it.

We may be able to remedy this by simply setting `shell=True` in the `subprocess.run()` call. See [here](https://docs.python.org/3/library/subprocess.html#frequently-used-arguments) for details.

**Comment by rod-glover** [comment]
:bulb:

**Comment by rod-glover** [comment]
I did not fully understand how environments are established for processes (and still haven't fully). Subprocesses inherit the environment they are spawned from. Hence I do not need to forward the environment from the invoking process to the subprocesses created by `subprocesses.run`.

This also means that cron is not doing something magic, and that I don't need to worry about it.
