### ISSUE TITLE
Add wheel to installation dependencies?

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/crmprtd#143]
During installation from our PyPI server, the following messages are emitted:

```
Using legacy 'setup.py install' for psycopg2, since package 'wheel' is not installed.
Using legacy 'setup.py install' for sqlalchemy-citext, since package 'wheel' is not installed.
```

This suggests it would be better to add `wheel` to the dependency list in `pyproject.toml`.

**Comment by jameshiebert** [comment]
I believe that this can be closed given Poetry and #161
