### ISSUE TITLE
Improve insert performance for observations

### ISSUE THREAD

**Issue by rod-glover** [pacificclimate/crmprtd#165]
We have a problem with bulk inserts of observations: There may be many redundant (already-existing) records which cause any given single insert to fail.

We currently have two approaches to this in the Python code: For blocks of data which appear to have few redundant records, we use a bisection strategy, and for blocks which have many redundant records, we use a single-insert strategy. The latter is particularly slow for reasons not understood. It seems possible that we could implement one or both of these as a stored procedure, which might reduce whatever overhead is involved in an insert (whether single or multiple records) query.

Possible better alternatives:
- Understand better what causes single insertions (or possibly any single query) to be slow.
- Use a different strategy in our Python query formulations to allow for inserts that violate the uniqueness constraint on the observation table without resorting to the single-insert strategy (or indeed the bisection strategy).
- Create a stored procedure that implements insert with fails internally.

**Comment by rod-glover** [comment]
A little searching reveals that since ver 9.5 PG has had an `ON CONFLICT IGNORE` clause for `INSERT`. Since we are now working with a version >= 9.5, we can use that. Holy 21st century, Batman.

**Comment by jameshiebert** [comment]
This would be *awesome*.
