### ISSUE TITLE
Fix PEP8 violations and add flake8 checking to CI

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/crmprtd#17]
Pull request #16 had a number of changes in it that were fixing up [PEP8](https://www.python.org/dev/peps/pep-0008/) Python Style Guide violations. This is great! I'm glad that @nikola-rados added these! However, the changes were a little distracting from the actual content during the code review.

Let's squash all of the PEP8 violations in a single go. Use `flake8` to identify all of the violations or use `autopep8` to fix as many as possible automatically. Then fix the rest. Then ensure that `flake8` is added to the `test_requirements.txt` and run as a test under TravisCI.

Let's branch this off of `master` as a hotfix branch, and then we can merge it into both `master` *and* `dev`.

**Comment by nikola-rados** [comment]
I'll get right on it!
