### ISSUE TITLE
Refactor ArgParse arguments in the scripts

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/crmprtd#26]
There are a number of command line arguments that are common to all of the download scripts that we have (or at least *should* be). Examples include `cache_file`, logging options, diagnostic mode, etc.

These arguments get repeated in all of the scripts. We should pull them all up into a common function that takes a parser as an argument and adds them all. As follows:

```python
# In crmprtd/__init__.py
def common_script_arguments(parser):
    parser.add_argument('-D', '--diag', ...)
    parser.add_argument(...)
    return parser
```

Then we can use this common code in all of the scripts and reduce the volume of repetitive code by quite a bit.

**Comment by nikola-rados** [comment]
Good idea, I'll get on it!

**Comment by nikola-rados** [comment]
@jameshiebert Do we want this change to occur in all ```crmprtd/scripts``` or just the scripts that control the pipeline?

**Comment by jameshiebert** [comment]
Let's start with just the 4 main pipeline controlling scripts. The remaining 7 may become obsolete through this refactoring exercise.
