### ISSUE TITLE
Add functionality for --diag

### ISSUE THREAD

**Issue by nikola-rados** [pacificclimate/crmprtd#38]
In the current data pipeline the ```--diag``` flag is not being used.  The purpose of this flag is to run the pipeline in diagnostic mode.  It should be passed into the ```align```,  ```insert``` since they interact with the database.

**Comment by jameshiebert** [comment]
Ideally, this diagnostic mode could be implemented as a [context manager](https://docs.python.org/3/library/stdtypes.html#typecontextmanager) that opens a new transaction before align and rolls back the transaction after insert (if in the appropriate mode).
