### ISSUE TITLE
crmprtd incorrectly assumes Pacific time

### ISSUE THREAD

**Issue by faronium** [pacificclimate/crmprtd#49]
Currently, crmprtd assumes that all timestamps are local and in pacific time. For NE BC this is incorrect and, generally, the timezone should be determined based on the lat/lon/time of any given observations. time is needed because timezones have changed historically.

**Comment by jameshiebert** [comment]
I *think* this was fixed by [this branch merge](https://github.com/pacificclimate/crmprtd/commit/54334717842990b1392da956ca1de9b69f13e82b) and specifically [here](https://github.com/pacificclimate/crmprtd/blob/master/crmprtd/swob_ml.py#L97). Could you confirm?

**Comment by jameshiebert** [comment]
Fixed in [release 2.0.0](https://github.com/pacificclimate/crmprtd/releases/tag/2.0.0)
