### ISSUE TITLE
Implement time range selection in process script

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/crmprtd#54]
implement a time range selection to the process script that could filter observations that our outside of the range. This would cut down on the number of skips that we receive on the networks that post rolling windows (and drastically speed up our insertion phase).

See #50

**Comment by faronium** [comment]
There is an error in how time ranges are being built into the URL. The web app that we are requesting data from requires timestamps of format:
 
%y-%m-%d/%H

note the slash and lack of :%M:%S

Currently, the code makes a url with %Y-%m-%d %H:%M:%S

So downloading date ranges from individual stations doesn't work.

At the URL side of things, what gets delivered is something like this:

https://prdoas2.apps.th.gov.bc.ca/saw-data/sawr7110?request=historic&station=33099&from=2020-01-22+20%3A51%3A39.422198&to=2020-01-22+21%3A51%3A39.422198

And that fails with HTML 400 with a web page returned saying:

"Invalid date format: 2020-01-22 20:51:39.422198 - Should be yyyy-MM-dd/HH"

Whereas the following succeeds:

https://prdoas2.apps.th.gov.bc.ca/saw-data/sawr7110?request=historic&station=33099&from=2020-01-01/12&to=2020-01-06/13

**Comment by jameshiebert** [comment]
Agreed that that's a problem, but it's unrelated to this issue. This issues is about the [`process`](https://github.com/pacificclimate/crmprtd/blob/master/crmprtd/process.py) script, which handles data *after* it's downloaded.

Opened a [new issue](#58) to track this.

**Comment by faronium** [comment]
Looks like wither the verify_date function needs to return a date as a string with the proper format or when the URL payload is being constructed strftime needs to be applied to convert the datetime object into a recognizable (to MoTI) string.

**Comment by faronium** [comment]
Sorry, my mistake

Climatologist
Climate Analysis and Monitoring Lead
Pacific Climate Impacts Consortium

W: 250 472 4476
M: 250 885 7994
