### ISSUE TITLE
Write log files compressed

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/crmprtd#6]
Our log files are filling up the root filesystem. There should be an option to `crmprtd` scripts to write log files with compression.

**Comment by nikola-rados** [comment]
Is this something I should look into @jameshiebert?

**Comment by jameshiebert** [comment]
Yeah, this is something you could take a look at. I'd look at two options:

1) Write log files compressed (as the ticket states). To do this, you'll want to check with Matthew that our log importer (the file watcher) can actually read compressed logs
1) Write *cache* files compressed. The ticket doesn't mention this, but that will probably be an even bigger user of disk space.
