### ISSUE TITLE
Infill not reflected in database

### ISSUE THREAD

**Issue by nannau** [pacificclimate/crmprtd#65]
This is a continuation of the problems from #64, trying to corroborate data from the logs vs entries into the databases themselves.

We will focus on the outage event of April 4th, 2020.

Here is the outage as seen in the database _before_ running the infill:

```
crmp=> select date_trunc('hour', obs_time) as hour, count(*) from obs_raw natural join meta_vars natural join meta_network where mod_time < '2020-04-09:10
:00:00' and obs_time > '2020-04-04:05:00:00' and obs_time < '2020-04-05:05:00:00' and network_name = 'MoTIe' group by date_trunc('hour', obs_time) order b
y hour;
        hour         | count
---------------------+-------
 2020-04-04 06:00:00 |  1698
 2020-04-04 07:00:00 |  1668
 2020-04-04 08:00:00 |  1675
 2020-04-04 09:00:00 |  1666
 2020-04-04 10:00:00 |  1643
 2020-04-04 11:00:00 |  1668
 2020-04-04 12:00:00 |  1612
 2020-04-04 15:00:00 |  1630
 2020-04-04 16:00:00 |  1697
 2020-04-04 17:00:00 |  1689
 2020-04-04 18:00:00 |  1682
 2020-04-04 19:00:00 |  1591
 2020-04-04 21:00:00 |  1683
 2020-04-04 22:00:00 |  1682
 2020-04-04 23:00:00 |  1674
 2020-04-05 00:00:00 |  1671
 2020-04-05 01:00:00 |  1661
 2020-04-05 02:00:00 |  1577
(18 rows)
```

Focusing on _one hour_ to run `infill_all` over, with the following parameters:

```bash
crmprtd_infill_all -S '2020/04/04 05:00:00' -E '2020/04/04 06:00:00' -a /auth/path -c "connection-string" -L /logging/path -N moti
``` 

and re-checking the database for these insertions reveals

```
crmp=> select date_trunc('hour', obs_time) as hour, count(*) from obs_raw natural join meta_vars natural join meta_network where obs_time > '2020-04-04:05:00:00' and obs_time < '2020-04-05:05:00:00' and network_name = 'MoTIe' group by date_trunc('hour', obs_time) order by hour;                                      hour         | count
---------------------+-------
 2020-04-04 06:00:00 |  2722
 2020-04-04 07:00:00 |  1668
 2020-04-04 08:00:00 |  1675
 2020-04-04 09:00:00 |  1666
 2020-04-04 10:00:00 |  1643
 2020-04-04 11:00:00 |  1668
 2020-04-04 12:00:00 |  1612
 2020-04-04 15:00:00 |  1630
 2020-04-04 16:00:00 |  1697
 2020-04-04 17:00:00 |  1689
 2020-04-04 18:00:00 |  1682
 2020-04-04 19:00:00 |  1591
 2020-04-04 21:00:00 |  1683
 2020-04-04 22:00:00 |  1682
 2020-04-04 23:00:00 |  1674
 2020-04-05 00:00:00 |  1671
 2020-04-05 01:00:00 |  1661
 2020-04-05 02:00:00 |  1577
(18 rows)
```

Which appears to have run successfully, and we usually wouldn't have looked twice. But checking for the recent inserts only (i.e. subtracting the last two queries) reveals:

```
crmp=> select date_trunc('hour', obs_time) as hour, count(*) from obs_raw natural join meta_vars natural join meta_network where mod_time > '2020-04-09:10
:00:00' and obs_time > '2020-04-04:05:00:00' and obs_time < '2020-04-05:05:00:00' and network_name = 'MoTIe' group by date_trunc('hour', obs_time) order b
y hour;
        hour         | count
---------------------+-------
 2020-04-04 06:00:00 |  1024
(1 row)
``` 

Which makes sense in the database. However, examining the _logs_ for each tag reveals that there were `'skips:', 5975, 'failures:', 0, 'successes:', 1210`. As a baseline, this makes it difficult to assess missing data because of the discrepancy (we expect 1024 successes, but the logs show 1210), particularly when trying to isolate a particular error that causes the missing data. 

It should be noted that the `Could not detect the station id` in #64 amounted to `205` occurrences, but amount to _no_ `failures` in the logs. So this is not likely to be the culprit of our missing data, and if it were, it's not reflected consistently between the database or the logs.

We believe that this degeneracy that we see on this simple example on April 4th, is happening for the other infills as well as the discrepancy can not be accounted for between the logs and the database. 

```
$ cat 04042020.txt | grep -c "Could not detect"
205
```

We are seeing a similar discrepancy here as well as for the 30th, 23rd and 12th outages.

**Comment by jameshiebert** [comment]
@nannau Would you consider this issue closed w/ your recent investigation complete?

**Comment by nannau** [comment]
I'd say so, yes. We couldn't ever figure out why these particular counts were different, but it is probably inconsequential because the infill scripts appear to be running correctly.
