### ISSUE TITLE
Adjust MOTI normalization log level

### ISSUE THREAD

**Issue by nikola-rados** [pacificclimate/crmprtd#67]
An error logged in moti's [normalization module](https://github.com/pacificclimate/crmprtd/blob/master/crmprtd/moti/normalize.py#L35) reports when it cannot find `obs-series` in the `xml` file.  It was discovered that this variable is missing mainly due to user permissions for different stations (see the note [here](https://github.com/pacificclimate/crmprtd/blob/master/scripts/infill_all.py#L144)). This is an expected behaviour and thus we should not be logging missing `obs-series` as an error but as a warning.

**Comment by jameshiebert** [comment]
Do you have any examples of what an empty `<observation-series>` element looks like? Just wondering whether there should be two cases:
1. The case where an `<observation-series>` contains `<observations>`s, but no station_id (ERROR)
1. The case where there are no `<observations>` (WARNING or ignore)

**Comment by nannau** [comment]
Here is an example of an empty series element looks like:

```xml
<?xml version="1.0" encoding="ISO-8859-1" ?><cmml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\Schema\CMML.xsd" version="2.01"><head><product operational-mode="official"><title>Observation from BC Meteorological Stations</title><field>meteorological</field><category>observation</category><creation-date refresh-frequency="PT1H">2020-04-29T11:44:13-07:00</creation-date></product><source><production-center>British Columbia Ministry of Transportation<sub-center>AWP</sub-center></production-center></source></head><data><observation-series></observation-series></data></cmml>
```

**Comment by nikola-rados** [comment]
@nannau where does the station id usually live in these xml files?

**Comment by nannau** [comment]
@nikola-rados it looks like it doesn't live in the xml file, but rather in the default file name...

a file name as an example is:

`sawr7110\?request\=historic\&station\=51137\&from\=2020-03-30%2F00\&to\=2020-03-30%2F05`

With the station ID being `51137`

**Comment by jameshiebert** [comment]
`crmprtd` doesn't use any information from file names as data/metadata (since the file could be a file on disk or a stream of bytes). Not using info from file names is generally considered best practice across PCIC.

I think what Nik is trying to ask is if there *were* `<observation>` elements in the series, where would the station ID show up?

**Comment by nannau** [comment]
It shows up in `<origin type="station"><id type="client">28072</id><id type="network">BC_MoT_28072</id></origin>` as an example from one with `<observation>` elements.
