### ISSUE TITLE
Fix "tests/test_align.py::test_closest_stns_within_threshold_bad_data" test

### ISSUE THREAD

**Issue by eyvorchuk** [pacificclimate/crmprtd#68]
This test fails on the lynx node due to the following error: `psycopg2.errors.InvalidParameterValue: Coordinate values are out of range [-180 -90, 180 90] for GEOGRAPHY type`.

**Comment by jameshiebert** [comment]
Can you provide more details?

+ What version of Python are you running?
+ What version of the relevant pacakges (`psycopg2`, etc.) are installed (output of `pip freeze` would help)?
+ What is the full output and traceback from running the test (output of `py.test -v -k closest_stns_within_threshold_bad_data`)?
+ Anything else that might help identify differences between the environment where you observed this error and the [CI environment where the test passed](https://travis-ci.org/github/pacificclimate/crmprtd/builds/683057179)?

**Comment by eyvorchuk** [comment]
- I am running `Python 3.6.8`.
- I have installed `psycopg2 2.8.5` and `SQLAlchemy 1.3.10`.
- The output is in the file below.
[test_closest_stns_within_threshold_bad_data error message.pdf](https://github.com/pacificclimate/crmprtd/files/4584068/test_closest_stns_within_threshold_bad_data.error.message.pdf)
- I didn't have `mock-1.11.1` installed, and I had `flake8-3.5.0` instead of `flake8-1.0.1`.

**Comment by jameshiebert** [comment]
I'm assuming that this is no longer an issue, as we do no longer support py3.6
