### ISSUE TITLE
Race condition in test_ec.py

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/crmprtd#74]
See the comment [here](https://github.com/pacificclimate/crmprtd/blob/master/tests/test_ec.py#L54) and example of this in action [here](https://github.com/pacificclimate/crmprtd/runs/870791141?check_suite_focus=true).

**Comment by jameshiebert** [comment]
One can fix this my [mocking out `utcnow`](https://stackoverflow.com/a/43800931) in the test function.

**Comment by cairosanders** [comment]
I'm stuck on this, and I'm not sure why it's not working. The solution you linked to wasn't working, so I tried this one https://docs.python.org/3/library/unittest.mock-examples.html#partial-mocking from the docs but with utcnow() instead of today() so:
```python
def test_makeurl_no_time_hourly(mocker):
  with mocker.patch('crmprtd.ec.datetime') as mock_t:
      mock_t.utcnow.return_value = datetime(2016, 1, 15, 21)
      mock_t.side_effect = lambda *args, **kw: datetime(*args, **kw)
      url = makeurl(freq='hourly')
      assert url == ('http://dd.weatheroffice.ec.gc.ca/observations/xml/BC/'
                   'hourly/hourly_bc_{}_e.xml').format('2016011521')
```
In both cases utc in makeurl is not using the mock. I don't have any experience with mocking so maybe I am missing something obvious?

**Comment by cairosanders** [comment]
Never mind. I just had to add `@pytest.fixture()`,

**Comment by jameshiebert** [comment]
So unfortunately @cairosanders , adding `@pytest.fixture()` to the head of the test as you did [here](https://github.com/pacificclimate/crmprtd/pull/80/files#diff-96dd396fce8f08b11acdf32dbaf6f03dR50) makes it so the test doesn't actually run. It turns that function into a [test fixture](https://docs.pytest.org/en/stable/fixture.html), which is code that is used to *setup* a test, not to actually run a test. You can see from the [test logs here](https://github.com/pacificclimate/crmprtd/runs/1098977966?check_suite_focus=true#step:6:121) that the `test_makeurl_no_time_hourly()` function is never run.

I took a shot at this issue, and it turned out to be harder than I was anticipating. It turns out that you can't actually mock a standard library function that's written in C or a C extension. So I had to wrap `datetime.datetime.utcnow()` in our module so that there was a hook to mock out. Take a look [at the branch I put together](https://github.com/pacificclimate/crmprtd/compare/bugfix/74_jmh) to see how *I* solved it (and notice that the test in question [does get run](https://github.com/pacificclimate/crmprtd/runs/1113236732?check_suite_focus=true#step:6:121)). I *think* that should do it.

Sorry that I tagged this a `good-first-issue`... it was much less straightforward than I thought!
