### ISSUE TITLE
Materialized view functions not in user's search path.

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/crmprtd#77]
When running the `crmprtd_process` script, it's possible to come across the following error:

```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) function matview_queue_refresh_row(unknown, integer) does not exist
LINE 1: SELECT matview_queue_refresh_row('collapsed_vars_mv', NEW.hi...
               ^
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
QUERY:  SELECT matview_queue_refresh_row('collapsed_vars_mv', NEW.history_id)
CONTEXT:  PL/pgSQL function "collapsed_vars_mv_obs_raw_insert" line 3 at PERFORM
```

This error shows up if you connect to the database with a user that doesn't have the materialized view functions (e.g. `matview_queue_refresh_row`) in its search path.

We should catch this Exception, and provide a more actionable and informative error message for the user.

**Comment by rod-glover** [comment]
Worth verifying if this function is actually in use any more, too. There is some legacy stuff.

**Comment by jameshiebert** [comment]
Well it's definitely in use... that's how the error was raised...

The 'collapsed_vars_mv' is a mapping of station (more precisely `history_id`) to variables for which that station has recorded observations. Without having to traverse the hundreds of millions of rows in `obs_raw`.

**Comment by cairosanders** [comment]
What is an action that results in this error? So that I can test the exception block.

**Comment by jameshiebert** [comment]
This might be a little bit tricky for you to recreate in a test environment, but I'm happy for you to give it a shot if you'd like.

As documented in this issue, the exception is raised when running the [`crmprtd.process.process`](https://github.com/pacificclimate/crmprtd/blob/master/crmprtd/process.py#L39) function, though you can probably narrow that down to either [call to `align()`](https://github.com/pacificclimate/crmprtd/blob/master/crmprtd/process.py#L63) or the [call to `insert()`](https://github.com/pacificclimate/crmprtd/blob/master/crmprtd/process.py#L71). Off the top of my head, my hunch is the latter, but play around with it a bit to isolate the case to be as narrow as possible.

To recreate this in a test environment, you will probably have to write your own fixture that builds off of the [`test_session` fixture](https://github.com/pacificclimate/crmprtd/blob/master/tests/conftest.py#L64) but adds an additional user that doesn't have any search paths configured. Then you'll need to connect with that user in a new session and return it to the testing function.

Again, it might be a little tricky, and I haven't through it the whole way through, so play around and let me or @rod-glover know if you run into trouble or need more guidance.

**Comment by cairosanders** [comment]
```quote
user that doesn't have any search paths configured
```
I'm not sure what this means exactly. Although I know it is what raises the error, I'm still not sure where to start with configuring it after looking at the code for a bit.

**Comment by rod-glover** [comment]
@cairosanders , to follow up on our IM exchange:
- A search path is a setting in the database engine that tells it in which schemas to search when it encounters a table name without a schema prefix (e.g., `my_table` vs. `my_schema.my_table`). (Note: "schema" here means a collection of tables; "schema" *also* means the particular definition and relationships of tables in a ... schema).
- The database holds information about users, including what their default search path is. For a newly-created user, that search path is `"$user", public`, which means a schema named the same as the user (if such exists), and `public`, which is nearly always present in all databases.
- You can set the search path by executing SQL of the form `SET search_path ...`. More info [here](https://www.postgresql.org/docs/10/ddl-schemas.html#DDL-SCHEMAS-PATH).
- To do that programmatically, use the `execute` method of a session, connection, or engine. E.g., `session.execute("SET search_path ...").
- The tricky part can be whether you need to make that setting at the session, connection, or engine level. The setting is valid in a different range of contexts for each case, and it can sometimes be the case during tests that you are not in the right context to have your SET command be effective where and when you need it.
- This does not set the default search path for the user, it sets it for the session / connection you happen to be in. This should be enough, but if it is not, then you'll need to find out how to set it for the user.

**Comment by jameshiebert** [comment]
> Worth verifying if this function is actually in use any more, too. There is some legacy stuff.

I should have heeded your warning, @rod-glover So I dug in a little more to advise @cairosanders on how to reproduce the error in testing. Turns out that this function is *not* in the PyCDS ORM :facepalm: 

```bash
james@basalt:~/code/git/pycds/pycds$ grep -r collapsed_vars_mv_obs_raw_insert *
[no results]
```

If we take a look at the production database:

```sql
crmp=> \df collapsed_vars_mv_obs_raw_insert
                                      List of functions
 Schema |               Name               | Result data type | Argument data types |  Type   
--------+----------------------------------+------------------+---------------------+---------
 crmp   | collapsed_vars_mv_obs_raw_insert | trigger          |                     | trigger
(1 row)
crmp=> \df+ collapsed_vars_mv_obs_raw_insert
 Schema |               Name               | Result data type | Argument data types |  Type   | Volatility |  Owner   | Security | Access privileges | Language |                                Source code                                | Description 
--------+----------------------------------+------------------+---------------------+---------+------------+----------+----------+-------------------+----------+---------------------------------------------------------------------------+-------------
 crmp   | collapsed_vars_mv_obs_raw_insert | trigger          |                     | trigger | volatile   | bveerman | definer  |                   | plpgsql  |                                                                          +| 
        |                                  |                  |                     |         |            |          |          |                   |          | BEGIN                                                                    +| 
        |                                  |                  |                     |         |            |          |          |                   |          |   PERFORM matview_queue_refresh_row('collapsed_vars_mv', NEW.history_id);+| 
        |                                  |                  |                     |         |            |          |          |                   |          |   RETURN NULL;                                                           +| 
        |                                  |                  |                     |         |            |          |          |                   |          | END                                                                      +| 
        |                                  |                  |                     |         |            |          |          |                   |          |                                                                           | 
(1 row)
```

So it's a trigger that was manually defined in the database, but not in the ORM... so any test database that you spin up won't have it present. *That's* why you're having trouble reproducing it. There are a couple of different paths forward, but maybe we should discuss in real time.
