### ISSUE TITLE
Update Meterorological Service of Canada URL

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/crmprtd#85]
From ECCC Datamart:

> ======================
> 
> Dear MSC Datamart users,
> 
> Please note that as of October 13, 2020, the following MSC Datamart access URLs will be decommissioned:
> 
>   *   http://dd.weatheroffice.ec.gc.ca
>   *   http://dd.meteo.ec.gc.ca
> These URLs are obsolete and only the following addresses will now be used to access the MSC Datamart data (*) :
> 
>   *   https://dd.weather.gc.ca/
>   *   https://dd.meteo.gc.ca

The URL [is hardcoded here](https://github.com/pacificclimate/crmprtd/blob/master/crmprtd/ec/__init__.py#L39) and needs to be either parameterized or at least changed.

**Comment by bhawesh96** [comment]
@jameshiebert , I'd like to take this up.
