### ISSUE TITLE
Installer is broken w/o requirements

### ISSUE THREAD

**Issue by jameshiebert** [pacificclimate/crmprtd#91]
[A recent change](https://github.com/pacificclimate/crmprtd/commit/cb3975665d209ca27a71#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7) [broke the PyPI Publishing Action](https://github.com/pacificclimate/crmprtd/runs/1488512607).

The cause of this is that the action doesn't actually install any of the package requirements, but then `setup.py` [makes an import](https://github.com/pacificclimate/crmprtd/blob/master/setup.py#L6) which [includes 3rd party packages](https://github.com/pacificclimate/crmprtd/blob/master/crmprtd/__init__.py#L54).

It turns out that the [3rd party packages imported in `crmprtd/__init__.py`](https://github.com/pacificclimate/crmprtd/blob/master/crmprtd/__init__.py#L54) are only used in [a function that's not actually used anywhere in the code base anymore](https://github.com/pacificclimate/crmprtd/blob/master/crmprtd/__init__.py#L211). Should we just remove it? The other option would be to only import 3rd party packages at run-time (inside the functions in which they are used) in this module. Since the code in question isn't run from `setup.py`, this would let us work around the existing problem.

@nikola-rados may want to weigh in here, as he and I are the only contributors to this function.

**Comment by nikola-rados** [comment]
Instead of removing it, wouldn't it just make sense to move the function into `scripts/` under its own module?

**Comment by jameshiebert** [comment]
Yeah, I'm not normally a fan of keeping code that's completely unused, but I suppose that this function *does* have some prospective utility. That's a good idea. I'll move it out of `__init__` and at least into its own module so that it's not breaking other very simple imports.
